### ISSUE TITLE
404 after translating url segment

### ISSUE THREAD

**Issue by cheatus** [Internetrix/silverstripe-fluent-extra-table#1]
Hi @Internetrix,
thank you for your plugin it helped me to fight against row size too large issue but I have another problem. After installing your module I get 404 after translating url segment as well as default fields such as Page Name or Navigation label doesn't have that orange indicator after actual translation. Is there a quick (or any) fix for this? 

Thanks,
D.

**Comment by bhofstaetter** [comment]
+1
